#+TITLE: Missing features in PPLs

I recently asked an open question on Mastodon:

#+begin_quote
What do you wish you could do with a PPL that no PPL currently allows you to do?
#+end_quote

And I got very interesting answers.

* Nicolas Chopin

#+begin_quote
To describe algorithms rather than describe models.

A Gibbs sampler where for component 3 and 12 you want to change the parametrization, or use a specific Metropolis step. Or one of the nonstandard gradient base samplers found in the paper by Titsias and Ppaspollopoulos, with preconditioners based on your prior. Or SMC samplers, etc.

It would be nice to describe any stochastic algorithm you can think of.
#+end_quote

* Matthew O'Meara

#+begin_quote
Debugging as easy as stepping through the code line by line. Of the ones I've used, in Pyro the tracing makes it hard, in Stan it's impossible.
#+end_quote

* Virgile Andreani

#+begin_quote
Infer parameters of stiff ODEs/PDEs without fear that I'm going to sample a parameter set which will break the numerical integration.
#+end_quote
* Jonathan Harrison

#+begin_quote
Inference with ODEs and PDEs.
#+end_quote

* Dae Houlilan

#+begin_quote
Focus on model building and spend less time finding reparametrization for difficult posterior geometries.
#+end_quote

* Moritz Shauer

#+begin_quote
Get the Markov blanker / conditional independence graph of the probabilistic program.
#+end_quote

- Inference compilation
- Parallel Gibbs samplers
- Gibbs sampler version of the Bouncy Particle Sample: [[https://arxiv.org/abs/1510.02451]]

#+begin_quote
Work with distributions that are discrete-continous mixtures
#+end_quote

- [[https://arxiv.org/abs/2103.08478][Sticky PDMP sampler]]

#+begin_quote
Run a code-to-code transformation over a probabilistic program.
#+end_quote

#+begin_quote
Use a reference measure of my choice to express target densities.
#+end_quote

- Wiener measure as in [[https://twitter.com/ChadScherrer/status/1509218598337740801]]

#+begin_quote
Treat inifinte dimensional distributions gracefully.
#+end_quote

Larry Shamala as well.
