:PROPERTIES:
:ID:       94c1d541-855b-49cc-8d88-958b8e5c50a1
:END:
#+title: Les marges d'erreur données par les instituts de sondage sont fausses
#+filetags: :pollsposition:

Les marges d'erreur données par les instituts de sondages sont une sous-estimation grossière de l'incertitude réelle à la "vraie" réponse à la question posée. Le but de chaque sondage est indiqué dans la question posée à chaque personne interrogée: quel serait le résultat de l'élection si elle avait lieu le weekend suivant le sondage.

C'est un problème vieux comme les statistiques, les instituts font une confusion entre intervalle de confiance.

Ce que nous cherchons à savoir, en tant que lecteurs de l'étude, est dans quel intervalle le score de tel candidat a-t-il X% de chances de tomber. La statistique fréquentiste ne permet pas de répondre à cette question.

Nous utilisons donc les statistiques bayésiennes pour inférer les marges d'errurs

* TODO Comparaison marges d'erreur bayésiennes et données

Autre problème, le bruit statistique lié à la taille finie de l'échantillon n'est pas la seule source d'erreur. La façon dont on forme les échantillons introduit une forme de biais: imnpossible de choisir les personnes inscrites sur les listes électorales complètement au hasard; la méthode de redressement nécessaire introduit un biais elle aussi (ou oublie d'en corriger). Ces biais sont propres à chaque paire institut/méthode. Ces biais sont à prendre en compte, ils sont importants. Mais ici nous ne considérons que le cas d'un seul sondage, ce que l'on peut dire en absence de toute autre information.

Il faut rajouter les indécis.

* TODO Graphe avec Xavier (marge instituts | marge bayesiennes echantillon | indecis)
