:PROPERTIES:
:ID:       62955ba8-482c-4841-86b3-cc6ec373f661
:END:
#+title: How to define urban areas
#+filetags: :public:

There is no universal definition for /urban areas/. The ones that exist rely on a distance threshold. For instance the INSEE (French equivalent of the Census Bureau) defines as urban areas as areas where buildings are distant from no less than 200m and that contain at least 2000 inhabitants.

However thresholds are arbitrary as such they have two disadvantage:
- We probably cannot compare urban areas from two different countries since the threshold is not chosen in a way that ensures that the defined cities are the same object;
- Even within a country like France urban areas may designate different objects as the threshold is not adapted to local specificities.

We need to find a method that does rely on a threshold but rather lets the definition emerge from the data itself.

* Street segments

We can use intersections as a proxy for population density, and try to infer the urban areas from maps. This has the extra advantage of being able to define cities in areas where census data is non existent or unreliable.

What makes me confident that we can delineate cities using the road network is that its construction essentially depends on two different processes. The roads between cities follow a logic of exploration, while the roads within a city follow a logic of the fragmentation of space.

[[file:images/urban-area-processes.svg]]

As a result we can hope for the /distribution of the street segments's length/ to be different:

[[file:images/urban-area-mixture.svg]]

Figure 1 in in [[https://www.nature.com/articles/s41598-018-22969-4][this article]] shows the distribution of the road length at the scale of the African continent and although a log-log plot we can imagine that the distribution is a mixture of several distribution. This reminds of what I did to [[id:5f60be02-f066-421a-87b5-677193755f96][Define sessions]] in a mobile application.

* TODO How does the landscape change when the 200m threshold is changed? :noexport:
