:PROPERTIES:
:ID:       decf58d3-66ec-4d34-be35-a310d824e89e
:END:
#+title: La Crise
#+filetags: :public:

* 1973

** Premier choc pétrolier

D'octobre 1973 à mars 1974 le baril de pétrole passe de $2.59 à $11.65
- Pic de production aux US
- Fin des accords de Bretton-Woods (dévalorisation cours du pétrole labellé en dollars)
- Déclaration d'embargo de l'OPEP suite à la guerre du Kipour


* 1979

Second choc pétrolier

* 1984

** Vive la crise

[[https://youtu.be/FbNdCQHWb-E][Emission diffusée]] en Février, présentée par Yves Montand. cite:inaculte2020

#+begin_quote
FLASH SPECIAL : Christine OCKRENT annonce une série de mesures d'urgence décidées par le gouvernement pour réduire le déficit de la sécurité sociale. C'est ainsi que débute cette émission consacrée à la crise économique, ses causes, ses effets, ses solutions. Yves MONTAND apporte tout son talent de comédien à jouer les Candides, anxieux de comprendre. Ses interventions forment le fil conducteur d'un montage alerte d'interviews d'économistes, de reportages, de mini-fictions prospectives. Visant à éclairer les français sur la situation économique de leur pays et du monde sans céder au traditionnel exposé didactique et austère, habituel en la matière.

 L'émission évoque d'abord l'apparente richesse des pays occidentaux qui masque, aux yeux de ses habitants, la réalité de la crise et les pousse à toujours désirer plus. Elle définit ensuite les symptômes et les manifestations du mal en insistant plus particulièrement sur le désordre monétaire international et ses conséquences possibles comme le refus des pays débiteurs de régler leur dette. Sont ensuite passées en revue les solutions illusoires baptisées les "YAKAS" puis les modèles économiques et les remèdes-miracles, aussi inefficaces les uns que les autres (monétarisme, keynésianisme, croissance zéro, guerre...). Viennent enfin quelques amorces de solutions possibles à travers une série d'exemples tant imaginaires que réels. L'émission se termine sur une vision optimiste de la nouvelle puissance européenne à l'aube du troisième millénaire.
#+end_quote
