:PROPERTIES:
:ID:       a9d4499d-b5f4-4676-8ada-f7a5a5c38681
:END:
#+title: How I take reading notes
#+filetags: :public:

Taking notes while reading serves two purposes:
1. It helps me think. These notes are /transient/ and do not need to be kept;
2. It helps me file important ideas for future use.

When I read a book about a *technical topic*, say bayesian inference, I open a new notebook on my Remarkable and scribble away. I come back to these /transient notes/ regularly to extract the core concepts, formulas, figures, etc that I want to remember. I type these /permanent notes/ directly on my computer. I sometimes use paper to organize transient notes as it is faster to re-arrange things. The transient notes should then be discarded as they clutter your mind with noise.

But this is only practical insofar as I am not reading books in the train or on my couch. For *lighter reading*, I will mark interesting paragraphs with an asterisk in the margin and take notes with an A7 (not bigger!) notepad that I always have in my pocket. I then move these pieces of paper around until I get a set of fairly self-contained, wannabe-permanent notes.
