:PROPERTIES:
:ID:       4778519d-4074-4ba7-bfbb-820d1966d56f
:END:
#+title: Culte de l'Union
#+filetags: :private:

- tags :: [[id:110eb391-3801-48b7-8533-c7a531e9cd71][Union Européenne]]


Culte de l'Union. Comme si notre monde était produit du /désir/. Ici, la /réalité/ n'a plus prise sur rien mais il convient cependant d'être /raisonnable/.

Debouts à coté des chefs d'Etats. On les a disposé bien à part, de façon symmétrique, de sorte à ce que l'équilibre soit conservé s'il fallait procéder à une purge photographique.

Culte de l'Union.

Ayant noté pendant la guerre du Pacifique, les populations de certaines ile de Mélasie ayant constate que les radio-opérateurs de troupes au sol semblaient obtenir

Ils constru

En réponse à la colonisation de la Mélanasie,

Le culte consiste entre à imiter les techniques et la culture occidentale: les

Le culte du cargoen espérant déboucher sur les mêmes effet

Certains seraient tenté de s'en moquer, mais le culte du cargo nous renvoie à nos propres biais. À toutes les situation où nous sommes amenés à agir par mimétisme, sans réelle réflexion sur le bien-fondé de notre démarche. Par pensée magique.

* L'UE meurt, vive l'Europe

Il est difficile de pointer de doigt le moment où le déclic s'est produit. Nés dans les années 80, j'ai été bercé de rêves d'Europe. Je me souviens encore du moment où j'ai reçu 20 euros en pièces, à l'époque où elles ne valaient pas plus que leur poids en métal. Elles n'étaient pas monnaie mais symbolisaient le rêve enfin achevé d'une intégration après tant de siècles d'affrontements sanglants.

L'humanité a cette capacité fantastique à créer des symboles, totems complètement abstraits, autour desquels de large groupes peuvent se retrouver et trouver un intérêt commun. La Nation, la République, l'entreprise sont autant d'entités qui vivent avant tout comme idée: elles ne se touchent pas, elles ne se mangent pas, elles ne peuvent pas être vues. Ces idées, lorsqu'elles se concrétisent, peuvent prendre des formes différentes.

Un ressort psychologique assez fort pour faire accepter une forme d'organisation est donc de lui attacher un symbole. Attaquer l'organisation c'est attaquer le symbole.

Lorsque la forme actuelle que prend l'Union Européenne déclenche ce mécanisme de défense spychologique dès qu'elle est attaquée. Lorsque vous lisez les europhiles dévier les critiques (légitimes) en parlant de "réforme", de "modification en profondeur" c'est bien de cela qu'il est question: croyant l'idée d'Europe même attaquée, ils déploient des efforts intellectuels démesurés pour tenter de sauver la forme dans laquelle elle se concrétise aujourd'hui.

Soyons clair une bonne fois pour toute dans ce texte. Si l'Union Européenne était réformable, ce serait bien évidemment le premier sujet de débat. Elle n'est pas réformable. Les traités imposent que les décisions soient prises à l'unanimité des 27 Etats membres

Je vais être honnête, parce que je suis persuadé que ceux qui vont me lire le pensent aussi: j'ai toujours eu un regard amusé, sinon méprisant, pour les fétichistes du Frexit. Ce n'est pas en lisant leurs analyses prémachées que j'ai changé d'avis, mais bien en m'intéressant aux traités eux-même, aux GOPEs, au fonctionnement des institutions et leur histoire. Quand bien même, je pensais, cela serait nécessaire, ça ne fait pas un programme politique.

Au contraire, c'est lorsque je me suis intéressé au pays qui m'intéressait, aux mauvaises décisions prise que la conclusion est devenue inévitable: il faut sortir du cadre de l'Union Européenne. Il faut retrouver notre souveraineté populaire, économique, monétaire. Ce n'est pas une fin en soi. C'est un moyen, mais ce n'est pas une option.

Peut-être le plus révoltant a été la lecture des GOPEs, ces "recommendations" émises par la Comission Européenne (qui, je le rappelle, n'est pas élue), et de pouvoir calquer dessus les politiques gouvernementales des 30 dernières années.

Jeunesse, réveille toi, tes rêves se meurent et tu regardes ailleurs. Les yeux pleins de bleu et d'étoiles jaunes, le coeur suspendu à un symbole.

On ne peut pas nier qu'il y ait chez beaucoup un /désir/ de nation européenne. Mais cette nation n'existe pas encore, elle existera sûrement, mais la transformation prendra du temps, des générations. La brusquer c'est la vouer à l'échec; l'inscrire dans cette union moribonde qui écrase les peuples c'est l'enterrer. Qui aurait idée

C'est la première fois que j'écris au sujet de l'Union Européenne, et je pense que ce sera la dernière. Je préfère parler de ré-industrialisation, de refonte de notre système éducatif, de santé, notre couverture sociale, nos centrales nucléaires, de PME et de souveraineté numérique.
