:PROPERTIES:
:ID:       75b82cba-444d-4b8f-a346-a8bd9ec540ad
:END:
#+title: Dette publique
#+filetags: :public:

- tags :: [[id:265e9ea6-4dc5-4471-aaf2-99ec70ff7024][Économie]] [[id:4c836563-ceff-4001-8bf0-8c8f3b0b64a0][Politique]]

* Commentaires de cite:boulo2021

Budget de l'etat (checher ministere action de letat et comptes publics): 338 Mds dont 42 Mds de charge de dette.
La dette représente 2000 Mds mais son paiement est echelloné sur 7 ans -> 14% du PIB. Comparer aux 33% pour un menage.
Etat ne va pas dispairaitre.
Etat possede du patrimoine

Dette liee aux prestations sociales? Comparer a d'autres pays moins sympas comme US et Chine

Creusement en 2008 -> Socialisation des pertes

Augmentation de la dette est due a la structure du fonctonnement de l'economie mondiale?

Impot differe sur les plus riches qui utilisent leur epargne pour emprunter. Ponzi scheme? Pourrait taxer a la place.

* Annulation

* Défaut

* Qui detient?

cite:boulo2021 48% par des etrangers (p82)
28% en 1999 -> 70% 2010 -> 52% grace au quantitative easing

Au RU et Japon, dette detenue majoritareiement par residents -> encourager ca en France
