:PROPERTIES:
:ID:       93fb8064-3398-4e7f-869c-cb03cc53fc90
:END:
#+title: Presidentielles 2022
#+filetags: :pollsposition:

* TODO Second tour
** TODO Template HTML pour sondages election second tour
- Si la date de sortie du sondage est la même qu'aujourd'hui -> "Aujourd'hui" sinon date
- Ecart avec 2e candidat
- Résultat en % des inscrits
- Carré avec couleur du candidat. Transparence donne l'échelle du score

| date sondage | Institut (lien vers l'étude) | Taille de l'échantillon | Scenarii | Resultat net |
** TODO Faire tourner sur 3-4 sondages
** TODO Graphe scenario le plus probable (sans incertitudes)

* TODO Premier tour
** TODO Template HTML pour sondages election premier tour
- Si la date de sortie du sondage est la même qu'aujourd'hui -> "Aujourd'hui" sinon date
- Ecart avec 3e candidat pour les deux premiers candidats
- Résultat en % des inscrits
- Carré avec couleur du candidat. Transparence donne l'échelle du score

| date sondage | Institut (lien vers l'étude) | Taille de l'échantillon | Scenarii | Resultat net |


* Sondages

On peut récupérer les sondages sur la [[https://fr.wikipedia.org/wiki/Liste_de_sondages_sur_l%27%C3%A9lection_pr%C3%A9sidentielle_fran%C3%A7aise_de_2022][page wikipédia]] dédiée, qui parait plutôt à jour.

** Format de données

*** Second tour

Il semble que la proportion d'indécis est importante; il est donc nécessaire de la prendre en compte. Mais il faut faire la distinction entre ce qui est de l'ordre du vote blanc/nul, du refus de se prononcer lors de l'étude

La difficulté est que les différents instituts de sondage ne présentent pas la même information. En effet, l'ensemble des inscrits peut être séparé entre:
1. Abstention
2. Vote blanc ou nul
3. Suffrage exprimé

**** Harris

Les deux questions suivantes sont systématiquement posées:
- "Et si le second tour de l’élection présidentielle avait lieu dimanche prochain, parmi les candidats suivants, pour lequel y aurait-il le plus de chances que vous votiez ?"
- "Et diriez-vous que vous êtes tout à fait sûr(e) de votre choix ou que vous pourriez encore changer d’avis ?"

Dans la première notice il y a mention de l'abstention, blanc/nul mais plus ensuite.

**** Elabe

"Et au second tour de l’élection présidentielle en 2022, si vous aviez le choix entre les candidats suivants, pour qui voteriez-vous ?"
    • Emmanuel MACRON
    • Marine LE PEN
    • Vous voteriez blanc
    • Vous n'iriez pas voter

**** Ifop

- "Si dimanche prochain devait se dérouler le second tour de l’élection
présidentielle, pour lequel des candidats suivants y aurait-il le plus de chance que vous votiez?"

Donne le pourcentage "ne se prononcent pas" -> pas de vote blanc/nul? Ce n'est vraiment pas clair.

**** Ipsos

"Si le 2nd tour de l’élection présidentielle avait lieu dimanche prochain et si vous aviez le choix entre les candidats
suivants, quel est celui pour lequel il y aurait le plus de chances que vous votiez au 2nd tour?"

"Personnes certaines d’aller voter n’ayant pas exprimé d’intention de vote : X %"

** TODO Entrer les sondages 2nd tour à la main dans un fichier yaml
** TODO Valider le yaml dans la CI
** TODO Plot 2nd tour polls using altair

* Site web

Il faut une page avec les [[https://projects.fivethirtyeight.com/polls/president-general/national/][derniers sondages]] pour le premier et deuxième tour.
