:PROPERTIES:
:ID:       d3df7965-07d3-46fb-8afe-30681c096f7f
:END:
#+title: Service public citoyen
#+filetags: :inprogress:public:

- tags :: [[id:4c836563-ceff-4001-8bf0-8c8f3b0b64a0][Politique]]

Rapport commandé par [[https://www.thedigitalnewdeal.org/]["Digital New Deal Foundation"]]. Avec le CEO de [[https://www.bayesimpact.org/fr/][Bayes Impact]] (Bob l'emploi).

Il faut commencer par noter que le rapport est un condensé d'intentions vagues, et qu'il se heurte à un obstacle de taille (la maintenance, voire plus loin). Il y a peut-être une ou deux idées à récupérer.

* Le numérique est un outil, il n'est pas normatif

A plusieurs reprises il est fait mention de la nécessité de redéfinir le service public; une grande partie des propositions qui sont faites plus tard découlent de ce caractère "inévitable":

#+begin_quote
Le service public de demain ne ressemblera pas à celui d'aujourd'hui (p.11)
#+end_quote


 #+BEGIN_QUOTE
 Face à ces nouveaux rapports de force, chaque société doit réintroduire une réflexion profonde sur les principes et la raison d'être du service public (p. 13)
 #+END_QUOTE

 #+begin_quote
Eviter la disparition du secteur public face à l'innovation du secteur privé (p.11)
 #+end_quote

 #+begin_quote
L'alliance est une nécessité... dans le sens de l'histoire (p.42)
 #+end_quote


 D'abord, le secteur privé ne vient pas en concurrence du service public si l'Etat décide de prendre en charge ce service par la suite. On peut prendre l'exemple de Doctolib, qui peut être socialisé si besoin est. Le développement d'initiative privées n'est pas une fatalité. Si les initiatives privées peuvent être problématiques pour les citoyens, ils ne sont pas une menace pour l'Etat. Ils peuvent même parfois coexister: hôpitaux/cliniques, écoles publiques/privées. C'est une question politique qui ne nécessite pas de réponse technique.

 De plus cela présuppose que l'Etat n'innove pas, ce qui est évidemment faux.

 Le numérique est un outil, il ne doit pas devenir normatif; comme le téléphone, révolution en son tmeps, ne l'est pas devenu. Il n'y a pas lieu de redéfinir, ou adapter, le sens du service public.

 La soumission à la sanction du vote fait qu'a priori les intérêts de chacun seront défendus.

* Une conception erronée du service public

 #+begin_quote
Répondre de façon personnalisée aux besoins de chaque individy, cela n'est-il pas le sens même du service public? (p10)
 #+end_quote

 Non. Vision individualiste qui n'est pas dans l'esprit de l'Etat et du service public qui agit dans l'intérêt commun comme émanation de la société.

 Rien à voir avec la liberté de choix.

 #+begin_quote
Garantir l'équilibre de la société en fonction d'un contexte donné et du choix des citoyens
 #+end_quote

 Oublient que l'Etat est une émanation de la société, qu'il emploie des citoyens. Un changement de politique au sein de l'Etat serait plus simple que rajouter une usine à gaz.

* Une fausse bonne idée

Le problème du software est la /maintenance/. Comment maintenant et prendre en charge des projets /one shot/ développés par des citoyens de façon indépendantes? C'est une perte d'argent à moins que des agents de l'Etat soient impliqués dans le développement de la solution.
Ou que l'Etat fasse lui-même des appels à contribution sur des sujets qui intéressent le plus grand nombre ou ceux qui en ont le plus besoin. Mais dans ce cas... quelle différence avec le programme des EIG qui pourraient être étendus. De même avec les programmes de Startup d'Etat.

Le système proposé est biaisé à la base. La population capable de problématiser ainsi, et qui a les capacité d'apporter des réponses technologiques à ses problèmes est aisée. Seule une approche "top down" permet de prendre en compte les besoins de /tout le monde/. En choisissant de financer ces projets plutôt que d'autres on introduit une distorsion dans l'investissement de l'Etat en faveur d'une population déjà privilégiée.

...Pas sûr que Bob l'emploi soit pertinent et/ou utilisé, est-ce que l'on a des retours utilisateurs ? En tant que techs on a toujours tendance à sous-estimer la valeur des agents sur le terrain.

Le problème de la frature numérique ne se réduit pas à l'accès inégal à internet (p.21)

*Principe de continuité* invoqué mais le point de la maintenance logicielle est complètement occultée.

Ne devrait pas être utilisé lorsque le contact avec un agent ne rendrait pas le service proposé plus pertinent.

* Une idée qui repose sur une vision bourgeoise de la société

#+begin_quote
La santé devient de plus en plus une affaire de style de vie qu'une affaire purement médicale... démultiplication des mouvements promouvant le bien-être (p19)
#+end_quote

Chiffre?

Le problème de ce programme est que l'Etat devra consacrer des ressources pour chacune de ces initiatives, c'est-à-dire vers des problèmes qui ne concernent qu'une partie de la population.

Raisonnement sur le [[id:b1942533-ba86-4600-a83a-98d860e5bf32][Chômage]] est complètement pété, suppose que problème est lié à un mismatch entre l'offre et la demande alors qu'il y a surtout très peu d'offre.

* Conclusion

Rapport écrit par des gens qui n'ont aucun prise sur le service public ou ce qu'écrire une application robuste qui doit être maintenue sur le long terme veut dire. Caractère normatif assez inquiétant. Rappelle le bouquin d'Hemelien et co.

La proposition la plus intéressante est p.37, sur les /challenges/ que l'Etat peut proposer aux citoyens, mais cela devient très similaire au programme EIG. L'Etat pourrait rediriger les aides publiques qu'il accorde aux entreprises privées via la caisse des Dépôts et la BPI vers ces projets d'intérêt général. Pourraient stimuler tout un écosystème privé autour de ces initiatives. Utiliser la commande publique pour des projets d'intéret généraux pour faire émerger un écosystème privé, plutôt que favoriser la création de sociétés prédatrices en accordant des aides aux autres.

Probleme = maintenance
voir https://blog.francetvinfo.fr/classe-eco/2016/11/01/we-dont-need-no-innovation.html
