:PROPERTIES:
:ID:       c83db8cf-2754-4192-b4ed-b6300ff2eda9
:END:
#+title: Use frequencies to vizualise uncertainty
#+filetags: :public:
#+LAST_MODIFIED: [2022-01-10 Mon 20:08]

One intepretation of the posterior samples we get from MCMC is that they correspond to /a world that is consistent the data that we observe/. From posterior distributions we often extract summary statistics that we then convey to the public.

Let's take infering people's intentions from poll data as an example. Two quantities are usually interesting to display:
1. The posterior distribution of intention to vote for the candidates
2. The posterior distribution of the difference of voting intentions between two candidates. A natural quantity of interest is the $P(n_i>n_j)$, i.e. the number of times candidate $j$ is ahead of candidate $i$ in our simulation.

People are more or less used to the concept of credible intervals so (1) is easy-ish to represent (I like forest plots with 95% CI for symmetrical distributions).To best represent (2) we need to convey what is means that "j is ahead of i in N elections out of 100".

This is a tricky one. Language matters.
- "Simulation of the elections"
- "Intentions compatible with the poll results"

A dynamic plot could be helpful here. Show points arrive one after the other with counters incrementing.
