:PROPERTIES:
:ID:       d6361b63-7810-4322-8951-88eb05a9d882
:END:
#+title: Projects are what we write for others
#+filetags: :public:

Project notes can easily be mistaken for /evergreen/ notes:
- they're structured;
- they can continuously be expanded;

To the point where one could be lead to think that they are one and the same. But they're not, and if one's not careful enough, project notes will quickly blow out of proportions. That's because not only they carry many ideas, but they are also written with the purpose of someone else reading the note.

However, projects often connect concepts together.

The situation here is slightly different from  [[cite:&ahrens2017]] since we may need to add some code / use data.

There are different ways in which they can manifest themselves

- blog posts
- separate projects (get their own repo, etc)

They're all

- But Cosma Shalizis's [[http://bactra.org/notebooks/][notebooks]] are a different beast. They are mostly accumulation of references and literature materials. What's the point of those?

The main distinction between notes and projects is that notes have something /universal/ about them. They are irreducible bits of knowledge, and can support many different projects. Projects, on the other hand, have something final to them.

Example of notes that can easily morph into a project:
- [[id:a1b1169c-d37c-454b-a07a-4b013212fa6f][Les notes du bac II]]
- [[id:316959ce-43d4-4e25-b445-cd2f5f651a15][Politics and statistics]]
