:PROPERTIES:
:ID:       0643e77a-2f30-4143-94b5-6b44051a22ef
:ROAM_REFS: cite:smith2017
:END:
#+TITLE: A Random Physicist Takes on Economics
#+CREATED: [2022-01-16 Sun 20:03]
#+LAST_MODIFIED: [2022-01-16 Sun 20:24]

p.16 - Says there is no textbook theory of inflation, only theories.

p.27 - The book is about several critiques of aspects of economics:.

- Economics is overly formal for its empirical accuracy
- Agents and what they do don’t matter as much as the realm of possibilities; agents are a sample from these possibilities.
- Expectations have no role to play
- Sticky prices are not so sticky
- SMD theorem (?) question how agents are combined in an economy.
- Economics as the study of functioning markets vs recessions may be the domain of more social sciences

p36 - Physicists have theoretical curves going through data, economists don’t.

p42 - Rational agents <-> close to equilibrium

* Random people

Gary Becker "Irrational behavior and economic theory" (1962) [[cite:&becker1962]]

Ideal rationality is not necessary to rederive some results, random agents are sufficient.
> p50 i feel there is something to his blueberry example but it makes no sense to me at this point.

p57 - If agents become correlated, the opportunity set does not change, only the way it is being explored.

p59 - Random agents don’t test on decision making while equilibrium does, human biais chooses the later.

* Another dimension

p63 - if none of choice is large you will siens ask your money because most of the volume of high dimensional shapes is near the surface. Spending all the money can be a result of random choices.

* Expectations

p79 - Expectations in economics brings information about the future into the present. We can project out inflation into the future no problem, the reverse is problematic.

p91 - "Reference price and nominal rigidities” -> sticky prices are not observed
p93 - sticky prices ate like elastic polymers. Looking at prices individually it will seems that there is no resistance to change. But considering all of them as a whole it becomes unlikely that a bunch of prices will move in same direction.
> But entropy can be overcome with coordinated action

p99 - Close to equilibrium theories tend to be simple in physics. So economics might be indistinguishable from a theory with radical agents close to equilibrium.
> "When the map is better than the territory" [[cite:&hoel2017]]

It’s all about finding the right effective theory at different scales.

p101 - Adam Smith "invisible hand"… "no part of his intention". Invisible hand may just be an entropic force.

p108- "Generalized theory of information transfer” vs "Mathematical investigations in the theory of value and prices “
Price is a measurement in imbalance: supply low or demand high. Price problem is not solving a knowledge problem, but an allocation problem.

Equilibrium is when information flow between supply and demand is enough to keep them in the opportunity set.
> what happens when it fails?

p116 - When details of human behavior matter economics is more like sociology

p122- "Finance itself could be considered the process by which we humans gain access to previously inaccessible opportunities in order to maiximize causal entropy"

All fails when people’s behavior start to correlate significantly.

p124- What is Okun’s law?

p126- "We’re not necessarily out to get the best deal without regard to others — we could well be random explorers of an abstract numerical universe"
