:PROPERTIES:
:ID:       bc588621-b365-4b61-a4ba-a3c029a8e514
:ROAM_REFS: cite:matthews2020
:END:
#+TITLE: One pollster's explanation for why the polls got it wrong
#+CREATED: [2022-03-08 Tue 08:12]
#+LAST_MODIFIED: [2022-03-08 Tue 08:29]
#+FILETAGS: :private:

Interview of [[id:9da40b6f-5255-4bda-96ce-6b803feb6871][David Shor]].

2020 election polls predicted that Biden would win but with huge misses, up to 11 points. In that sense polling was not better in 2020 than it was in 2016 and 2018, it's just that Biden's lead was robust enough.

David thinks that it is due to a sorting bias, i.e. the fact that people who answer polls even controlled for demographics are very unlike the typical voter. His view is consistent with [[cite:&gelman2016]].

Assumption of polling is that you can take the responses of poll takers, weight them according to race, education, gender, etc. and get the views of the general population. This use to be roughly right but changed in 2016.

#+begin_quote
But it turns out that people who answer surveys are really weird. They're considerably more politically engaged than normal and they have much higher agreeableness. [...] They also have higher levels of social trust.
#+end_quote


#+begin_quote
This gets to something that’s really scary about polling, which is that polling is fundamentally built on this assumption that people who answer surveys are the same as people who don’t, once you condition on enough things. That can be true at any given time. But these things that we’re trying to measure are constantly changing. And so you can have a method that worked in past cycles suddenly break.
#+end_quote

The polling business has become more complicated now that simple statistical weighing with a few variables does not work anymore:

#+begin_quote
There used to be a world where polling involved calling people, applying classical statistical adjustments, and putting most of the emphasis on interpretation. Now you need voter files and proprietary first-party data and teams of machine learning engineers. It’s become a much harder problem.
#+end_quote

Against the /shy Trump voter/ narrative:

#+begin_quote
People tell the truth when you ask them who they’re voting for. They really do, on average. The reason why the polls are wrong is because the people who were answering these surveys were the wrong people.
#+end_quote
