:PROPERTIES:
:ID:       80edec20-bb5f-4366-9c16-6b7a7195453c
:ROAM_REFS: cite:turrell2021
:END:
#+TITLE: The Star Builders: Nuclear Fusion and the Race to Power the Planet
#+CREATED: [2022-03-09 Wed 14:59]
#+LAST_MODIFIED: [2022-03-09 Wed 14:59]

* Notes :noexport:

p11 - NIF has 10 million moving parts, space shuttle has 2.5 million. Arguably more complicated. »

p44 - Renewables won’t cut it. At scale they’re in competition for space needed to grow food for instance. Energy is diffuse, there’s no "vein" of sunshine. Energy is intermittent. Maximum rate of deployment is the problem.

p103 - Fusion is a way to get geopolitics out of energy production

p150 - Halite and Centurion experiments on nuclear fusion

p208 - Nuclear fission is the safest energy in the world with 20 deaths per exajoule produced

p224 - Steps to energy production
1. Plasma hotter than center of sur
2. Get heat out of plasma to heat water
3. We have a huge source of neurons that will impact everything
4. Breeding tritium

p237 - Costs of fusion etc (takes notes, important for future référence)

Rate of deployment of different energys sources? Footprint?

p243 - Renewables are not natural disaster proof (think super eruption)

p248 - fusion could produce exhaust speeds orders of magnitude greater than chemical and fusion rockets
