:PROPERTIES:
:ID:       f419181f-dd28-4373-89de-1784748f82b7
:ROAM_REFS: cite:lemoine2022
:END:
#+TITLE: La démocratie disciplinée par la dette
#+CREATED: [2022-03-07 Mon 18:43]
#+LAST_MODIFIED: [2022-03-07 Mon 18:56]

* Notes :noexport:

p32 - Détenir de la dette, et choisir de prêter ou non à la puissance publique, doterait d'un pouvoir politique concurrençant le droit de vote aux élections. Noté par Karl Marx. C'est cet autre coté de la dette publique qu'on oublie tout le temps.
La détention d'une partie de la dette publique équivaut à la détention d'un actif politique.

L'Etat vit à crédit et finance les épargnants au lieu de les taxer. Un effet pervers s'installe donc. L'endettement revient à prendre les revenus des classes moyennes et les distribue aux gens aisés.

Pire l'Etat se fait garant de la dette publique, et l'échange en contrepartie de réformes sociales. C'est le livre dans lequel il faut aller piocher ce genre d'exemple.

IN the US, half of the emitted bonds are owned by 1% of the population (source?). Et en France?

En 2016 la BCE ferme le robinet du refinancement des banques Grecques (source?).

p88 marché obligataire américain = 18 000 billion dollars. Much of the financial system depends on those having value.

p102 - Comédie de la BCE qui n’intervient que sur les marchés secondaires pour "laisser le marché donner le prix", mais dans les faits supporte l’action des états.

p133 - L’idée qu’il faut se protéger de la démocratie apparaît à plusieurs reprises. Protéger qui ? De quoi ?

p152 - If financial markets need it, shouldn’t they pay for it?

** TODO Retrouver les extraits où il est question de se protéger de la démocratie
** TODO Liste des créditeurs de la dette française, distribution
