:PROPERTIES:
:ID:       0bdd40d5-21a2-4f5e-9f14-8a5738513569
:END:
#+title: Monetary creation
#+filetags: :public:

The fed creates money via three different channels:
- Bank reserves
- Debt

#+begin_comment
I think the word debt carries too much baggage and should probably be replace with something else that reflects what it is a lot better. I feel like the word stay the same but the meaning has drifted.

- Debt in 1971
- Debt after the end of Bretton Woods
- Changes in regulation
- Changes in how the Fed operates
- Who sets the real meaning of debt
- What is the relationship between [[id:8e188107-bab9-438e-bc23-f9863f50f783][Public Debt]] and [[id:ee38c3b2-8037-4f20-9c78-701a629f140a][Money]]?
#+end_comment


There are several ways to create money, and one is through [[id:8e188107-bab9-438e-bc23-f9863f50f783][sovereign debt]]. This is constrained by requirements on [[id:e16de427-80a4-47a8-8787-9c6b8fe8adc2][Liquidity reserves]].

- Post 2008, Bale III forces banks to have a fixed ratio "High Quality Assets" in their reserves. See the [[https://www.bis.org/publ/bcbs238_fr.pdf][the document]]
- Here is the ECB's [[https://www.ecb.europa.eu/pub/pdf/other/gendoc2011en.pdf?c7c23fd7c60fb4477f32c5c922d60eb3][implementation of their monetary policy]]

My guess is that monetary creation through the financial sector is more adapted to what is really happening in the economy. Otherwise money is only injected through public spending.

To read on the ECB system:
[[https://www.ecb.europa.eu/pub/pdf/scpops/ecb.op282~6017392312.en.pdf][Demand for central bank reserves and monetary policy implementation frameworks: the case of the Eurosystem]]X

* Questions

Most of these questions are ill-posed and will only make sense to me:

- What happens when you keep increasing the amount of money available?
- What happens if we /don't/ increase the amount of liquidity available?
- What does it mean we cannot afford something?
- Is LVMH a HQLA (interest rates on debt are negative)? They absorb the excess demand for bonds.

** TODO Look at LVMH bond yield over time, and frnehc bonds and german bonds
The idea is that if banks are really thirsty for HLQA they will first deplete gvt bonds and THEN LVMH.
** TODO Look at the way LCR is computed
