:PROPERTIES:
:ID:       8cc5ef87-891b-4db0-9629-87e9f64b85b3
:END:
#+title: Tout découle de l'égalité des droits
#+filetags: :public:

Je pense que le capital reste une bonne grille de lecture des rapports de force dans la société, et une des composantes sur laquelle on doit se concentrer, mais elle est moins pertinente aujourd'hui. La base de la base, le premier axiome de notre société est donné par le 1er article de la DDHC:

#+begin_quote
Les hommes naissent et demeurent libres et égaux en droit. Les distinctions sociales ne peuvent être fondées que sur l'utilité commune.
#+end_quote

Or un effet néfaste du capitalisme est la distorsion de la réparition du pouvoir dans la population. Chercher l'égalité en droits avant *l'égalité* est plus générale, plus pertinente, moins controversée et plus générale.

L'éco n'est un pas un bon thème de lecture. Le déséquilibre des pouvois dans une société démocratique est une grille plus intéressante. J'en viens après avoir lu des papiers de philosophie de la taxation où l'argument le plus convaincant en faveur de la taxation progressive est d'empêcher les plus riches d'entraver le fonctionnement de la démocratie: le pouvoir que l'on exerce est d'autant plus import que l'on est riche.

D'un point de vue pratico-politique touc change. Dans une époque où les contraintes sont imposées au nom de la /liberté/, l'angle d'attaque est bien meilleur que "ce truc de gauchistes qui veulent nous prendre notre argent".

[[id:394178f6-5dcf-4e4b-a677-647b13d71899][Les inégalités de richesse mettent la démocratie en danger]], cette idée a été défendue à plusieurs moments de l'histoire:
- Dans la Grèce antique par Démocrite
- Theodore Roosevelt et son Square Deal
- Frankling Roosevert et son New Deal

* TODO Retrouver discours sur l'institution de l'IR :noexport:
Effort de guerre et reconstruction, qui a permis l'acceptation de taux marginaux > 90%

* References
- Discussion / [[https://twitter.com/remilouf/status/1478349831324188676?s=20][Thread twitter]]
- [[https://jacobinmag.com/2021/12/equality-of-power-socialism-exploitation-income-inequality-theory][The equality that socialists care about most is equality of power]]
