:PROPERTIES:
:ID:       ee8b237a-fa4a-4265-9b7f-972a3dd9b45f
:END:
#+TITLE: Horsehoe prior
#+CREATED: [2022-02-11 Fri 15:30]
#+LAST_MODIFIED: [2022-02-16 Wed 14:59]

We can define the Horseshoe prior in the general context of a [[id:e878015f-6716-44e8-a79b-6b9fa2cbc89b][gaussian scale mixture]] model :

#+begin_src latex :results raw :exports results
\begin{align*}
  z_i &\sim \operatorname{Normal}(x_i^T\beta,\; \sigma^2\, \omega_i^2)\\
  \sigma^2 &\sim \pi(\sigma^2)\, \mathrm{d}\sigma^2\\
  \omega_i &\sim \pi(\omega_i)\, \mathrm{d}\omega_i\\
  \beta_j &\sim \operatorname{Normal}(0,\; \lambda_j^2\, \tau^2\, \sigma^2)\\
 \lambda_{j}  &\sim \operatorname{C}^{+}(0, 1)\\
 \tau &\sim \operatorname{C}^+(0,1)\\
\end{align*}
#+end_src

#+RESULTS:
\begin{align*}
  z_i &\sim \operatorname{Normal}(x_i^T\beta,\; \sigma^2\, \omega_i^2)\\
  \sigma^2 &\sim \pi(\sigma^2)\, \mathrm{d}\sigma^2\\
  \omega_i &\sim \pi(\omega_i)\, \mathrm{d}\omega_i\\
  \beta_j &\sim \operatorname{Normal}(0,\; \lambda_j^2\, \tau^2\, \sigma^2)\\
 \lambda_{j}  &\sim \operatorname{C}^{+}(0, 1)\\
 \tau &\sim \operatorname{C}^+(0,1)\\
\end{align*}


It is characterized by the global ($\tau$) and local ($\lambda_j$) /shrinkage parameters/ that follow a half-Cauchy distribution.

* How does it work?


* Sampling

We can use the fact that the [[id:45ccc897-f07c-4adc-9142-9ae8870fbddc][Half-Cauchy distribution]] can be written as the mixture of two [[id:61967eb9-6a01-4d0c-a1e9-de25f68f5f4a][inverse-gamma distribution]]s to write the conditional posterior distributions for the local shrinkage parameters.

* COMMENT Intepretation

If we use the decomposition of the [[id:45ccc897-f07c-4adc-9142-9ae8870fbddc][half-Cauchy distribution]] so that:

#+begin_src latex :results raw :exports results
\begin{align*}
  \lambda_j^2 | \nu_{j} &\sim \operatorname{InverseGamma}(1/2, 1/\nu_{j})\\
  \nu_{j} &\sim \operatorname{InverseGamma}(1/2, 1)\\
\end{align*}
#+end_src

#+RESULTS:
\begin{align*}
  \lambda_j^2 | \nu_{j} &\sim \operatorname{InverseGamma}(1/2, 1/\nu_{j})\\
  \nu_{j} &\sim \operatorname{InverseGamma}(1/2, 1)\\
\end{align*}


and integrate out the $\lambda_j$ we find:

#+begin_src latex :results raw :exports results
\begin{align*}
  \beta_j \sim \operatorname{Cauchy}\left(0, \frac{2\tau\sigma}{(2\nu_{j})^{1/2}}\right)
\end{align*}
#+end_src

#+RESULTS:
\begin{align*}
  \beta_j \sim \operatorname{Cauchy}\left(0, \frac{2\tau\sigma}{(2\nu_{j})^{1/2}}\right)
\end{align*}

In other words the Horsehoe prior consists in putting a [[id:31c8e78e-892c-4a73-b5d1-1d9b2e8a7fa7][Cauchy]] prior over each regression coefficients. [[cite:&makalic2015]]
