:PROPERTIES:
:ID:       6db43c67-bc23-480f-92e8-e8c971f61eb2
:END:
#+title: What I am reading
#+filetags: :public:


My reading feeds this digital garden in a process that starts with [[id:a9d4499d-b5f4-4676-8ada-f7a5a5c38681][taking reading notes]]. I try to read only a few book at the time; the following are currently on my bedside table:

- Julian Jackson - De Gaulle
- Jacob Goldstein - Money
- Daniel Friedman, William Byrd, Oleg Kiselyov & Jason Hermann - The Reasoned Schemer

* The pile

There are [[id:18bb96ef-f68c-4634-8550-8272c5e6515b][quite a few books waiting to be read]] in my house. For money that wasn't spent in vain (can't say it was always /well/ spent), see [[id:911c1ce7-5f95-4047-b724-91cd06761533][what I have read]].

* Contribute to my education

I feel that [[id:911c1ce7-5f95-4047-b724-91cd06761533][what I have read]] and the current list is /very low variance/ and I'd appreciate the following kind of suggestions:

- (Science)Fiction
- Anything with a high vantage point. Think Sapiens, Turchin, etc.
- Anything that would stand out if they were in [[id:18bb96ef-f68c-4634-8550-8272c5e6515b][the reading pile]] because they have a very different point of view.

Since [[id:f139e256-9a3a-43a9-99d0-03ff7a0c2446][ideas are rarely right or wrong]], I am always after a broader perspective.
