:PROPERTIES:
:ID:       5896070e-8664-41f8-96c0-310925d1c83d
:ROAM_REFS: cite:oneill2018
:END:
#+TITLE: Taxation: philosophical perspectives
#+filetags: :taxation:economics:philosophy:public:

Questions I hope to answer:
- On what basis do we justify taxation and redistribution?
  - Efficiency?
  - Property rights?

* Overview
:PROPERTIES:
:PAGES: |1--13]
:END:

There is a tension between two philosophical views of taxation:
- /Robert Nozick/ argues that property rights were pre-political, and thus the state cannot interefere with these rights. It should be kept at its strict minimum to enforce these rights; transfers should operate via philantropic work. As a result, /Nozick/ sees taxation as "forced labor". It has a strong influence on contemporary debates. cite:nozick1974
- For /John Rawls/, property rights are not a pre-political constraints on the operation of economical and political institutions, they are creations of the "basic structure" of society. Tax rules are also part of this basic structure. A tax system is just when it contributes to a system that satisfies the principles of justice. In his conception of Justice, Rawls endorses a steeply recipient-oriented inheritance and capital trasnfer tax. cite:rawls2020,rawls1958

  cite:murphy2002
