:PROPERTIES:
:ID:       bfa82d9a-5327-4f39-ab2b-7bd913290d17
:END:
#+title: 2022-05-27

* The Ups and Downs of automated Code Checking Software

This article is about software that can automatically check that the building is compliant with code (often 100k+ pages) from its design. This requires to be able to do 3 things:

1. Represent the construction in a computer program;
   Medium-sized building may require to label 100k+ parts, which is virtually unfeasible.
2. Represent the code in a computer program;
   Difficult because some statements are ambiguous and are hard to implement as a rule in a computer program (/without effort and prior knowledge/ for instance).
3. Convince the authorities that if a building passes the automated code check it is compliant with code.
   Most projects don't even attempt to do this, even though a system is useless if authorities won't accept its output.

No software does everything, but some tools exist and are recognized for solar installations, and energy code compliance. These three projects, unlike the ones who failed are very narrowly focused. They also did not try to solve any complex technical problems, they are mostly about drop-down menus and textboxes. They ignore problem 1 and 2 to focus on problem 3.

 #+begin_quote
[M]ost new ideas and innovations in the construction industry have been tried, and often much earlier than you might expect. [...] A corrolary of this ideas is that if you want to improve the construction industry, you should have at least some idea for why th idea you're considering didn't work previously.
 #+end_quote

* Make America Great again
From /Faster Please!/

We can identify two dates where "America started going off rails"
- 1972 is the end of Project Apollo
- 1965 is the Immigration and Naturalization Act

The author associates the 1965 landmark with an anti-globalization date; although that's more of a culturalist landmark. Anti-globalization would be the end of Bretton-Woods. Generally, associating people against immigration with people who are against free trade is disingeneous.
