:PROPERTIES:
:ID:       729275ba-934c-43ca-99dc-487240c14710
:END:
#+title: Org-mode is superior to Jupyter notebooks
#+filetags: :public:


- tags :: [[id:15a9ee78-16e4-4df9-b01b-60ef4cbe0a44][Workflow]]

(for me, and probably for you too if you're reading this!)

* It is superior

- We can get the same functionalities (besides widget) with the appropriate configuration
- I am in a real text editor
- I can connect to kernel in a REPL and explore its state
- I can copy code from other places on my HD
- I have access to my emails
- Easier to navigate within the document itself. I typically use a single org file when I would have needed several jupyter notebooks;
- Export in other formats is easy and highly customizable.
- I can combine several languages in the same document (mainly shell and sqlite)
- You can *version control* your org files!

* But not perfect

- Few people know and want to learn emacs which has a steep learning curve; working with others can be a challenge;
- The figures are not saved with the document (reason why they play nice with version control), /but/ we can easily export the org document to pdf for review.
