:PROPERTIES:
:ID:       9980ae28-68d4-4e29-9248-d661ccd85ab8
:END:
#+title: 💻 Working on now
#+filetags: :public:

I enjoy work and my personal projects (open source) very much, and they keep me very busy. I am also trying to [[id:058ec62c-6022-4eeb-b0a0-e88a75a8b761][do other things with my life]]. My interests have recently shifted towards Large Language Models, but my statistics and symbolic background are still very relevant!

* Sampling sequences with Large Language Models

I am convinced that the current way we [[id:27582309-04c5-436a-9c6f-5c519148e701][generate sequences]] with Large Language Models is suboptimal. We can do much better than [[id:755eb8da-0279-45fb-9297-58df59a4e538][greedy search]], [[id:412ada6d-997b-4e9e-8940-4c66e92ca00f][multinomial sampling]] or [[id:57c3b765-3559-45ce-a3cc-a8a21ed32483][beam search]]. I think that [[id:3a1f486b-d799-43f7-8726-1276b1ffdfb4][SMC steering]] is more promising.

* Guided generation with Large Language Models

* Optimizing inference time

* Outlines

I am also working on an Open Source library that provides guided generation, [[id:2c8ea1ef-d64e-479a-b295-f7caee097e8c][Outlines]]. It also helps me learn everything LLMs.
