:PROPERTIES:
:ID:       14236af7-7de2-4ff1-9c66-381ef6ea8156
:END:
#+title: Les mesures d'austérité conduisent à une hausse des inégalités
#+filetags: :public:

Le Fonds Monétaire International, bien qu'il ne bouge pas de sa ligne de "réajustement" budgétaire, reconnaît néanmoins que les politiques d'austérité dans les pays occidentaux ont conduit à une hausse des inégalités :IMF2012

#+begin_quote
In advanced economies, redistributive fiscal policy
has historically played a significant role in reducing
inequality in market incomes. However, reforms since
the 1980s have typically contributed to increased
income inequality by lessening the generosity of social
benefits and the progressivity of income tax systems
[...]
Overall, the data point to a strong
negative association between social spending and
income inequality
(p.50)
#+end_quote

Le rapport du FMI a plusieurs avantages pour nous. D'abord, il ne peut être accusé d'être biaisé puisque le FMI a défendu et défend toujours les mesures d'austérité budgétaire. Ensuite il s'efforce  d'anlyser les données en sa poition, principalement de l'OCDE. Leurs conclusions ne sont pas très tendres avec leurs recommandations:

#+begin_quote
Based on the results for 17 OECD
countries, a consolidation amounting to 1 percent-
age point of GDP is associated with an increase
of about 0.6 percent in inequality of disposable
income (as measured by the Gini coefficient) in
the following year.
#+end_quote

Autre effet intéressant, ils trouvent que le ratio taxes directes / taxes indirectes (suposément un proxy pour le manque de progressivité du système fiscal) est encore plus fortement associé avec une hausse des inégalités. Finalement, fait encore plus étrange, ils trouvent que ce qui affecte le plus les inégalités positivement sont les subventions des entreprises publiques:

#+begin_quote
dies is sensitive to estimation methods, the
seemingly unrelated regression estimates suggest that
an increase in subsidies of 1 percent of potential
GDP is associated with a 0.5–1.1 percent reduc-
tion in inequality. Of course, a policy to reduce
inequality that targets these subsidies to low-income
consumers would be even more effective and also
#+end_quote

(p.58) Montrent q'un épisode de consolidation fiscale peu conduire à une augmentation des inégalités de 2%.
