:PROPERTIES:
:ID:       f6592dcf-e288-4c9f-a231-2d4a9ea88501
:END:
#+title: Euro
#+filetags: :public:politique:

- tags :: [[id:1a53642d-c03e-4ae9-92e2-e164869927b3][Monetary systems]]

* Arguments in favor of the euro

Regarder [[https://t.co/15vjPnkGOz?amp=1][Cette conférence de David Cayla sur la rationalité économique qui sous-tend l'euro]].

Débat Attali, Chevènement, Garaud
https://www.youtube.com/watch?v=2RvJHmYbECk&feature=youtu.be

** TODO States can borrow at much better interest rates
** TODO La disparition des taux de change est bénéfique pour l'intégration économique

This could have introduced perverse effects in terms of fuind transfers. Need some digging and data. Remove
cite:stiglitz2016 (p46)

*** yes, but

This had perverse effects, cite:stiglitz2016 (p46). We didn't need a common currency to integrate China in the globall supply chain. cite:stiglitz2016

** Inflation rates converge

Ok but how is that relevant?
*** TODO Show on curve

** L'Europe c'est la paix sociale qui pèse

See cite:stiglitz2016 (p35-36). But the question is ill-posed: is a monetary union /necessary/ to achieve this goal ? We need consensus first, but everyone is doing different things.

Wrong, see the Greece crisis cite:stiglitz2016 (p59)

** Si ça marche aux US avec 50 état ça peut marcher avec 19 en europe

Il existe 3 mecanismes d'ajustment aux US qui n'existent pas en Europe cite:stiglitz2016 (p89)
1. Meme langage et programmes de sécurité sociale etc. Migrer d'un état à l'autre est très aisé.
2. People in the States think of themselves as american first.
3. Après une crise, un Etat recevra de l'aide du gouvernement fédéral. Les programmes d'aide sont nationaux en Europe.
4. Système bancaire unifié

** TODO Grâce à l'Euro l'Europe est prospère

Following are taken from cite:stiglitz2016 p65 onwards

In the crisis:
- In Spain unemployment fell from 26% in 2013 to 20% in 2016. BUT Spaniards left & GDP/capita still below.
- Stagnant GDP. Cumulative growth really low, hides negative in Greece, even Germany hailed as an example is low.
  /Compare to Great Depression contraction/
  /Compare to non eurozone country/
  /Compare to US/
- Unemployment has risen
- Inequality has risen

*Yes but* everyone was affected by the 2008 downturn. Lost decade in Europe + loss of compounding effects. Well we can probably fit a model where we look at what it would have looked like had we been like the US.

Generally:
- Look at euro area GDP trend and /compare to the US/.
- Even Germany has shit economic performance


**** TODO Reprendre le graphe de X-alternative sur l'industrie


*** Counterarguments

/It would have been worse without the euro./
/Maybe it's about changes in the economy that affected the eurozone that has nothing to do with the currency./

cite:stiglitz2016 (p81)
