:PROPERTIES:
:ID:       98630aaf-4ed8-4678-87d9-8088f7893a54
:END:
#+title: My daily routine
#+filetags: :public:

I know /within the first two hours/ of my day if it is going to be productive or not. Everything is geared towards making the creative work happen then. I used to wake up at 5am and write a few thousand words before getting breakfast, but it is unfortunately now impossible without waking up my two youg children. I don't have time to myself until around 8:30 am.

I have found that preserving creativity and clarity of mind is more about how you experience your environment and what you choose to pay attention to. Making breakfast, having coffee, chatting with the kids and even pushing them through the door is part of a flow, and if I make an effort to be conciously present it feeds my creativity more than it depletes it. Being exposed to other people's ideas and opinions, however, is a creativity sink. My mind is suddenly filled with other people's voice and I cannot hear mine anymore. That's why I go for a full internet ban until 10am. The US is asleep, most French people are not at work yet. I am not needded, but I need this time for myself.

I have a few guitars, and one sits right next to my desk. When I need a break during the day I instictively grab it and work on my scale, play a few tunes I know, work through a new one. 15-30 minutes is all I need to completely empty my head, start afresh, and I even become a better player over time! Don't tell VCs, I usually work on my scales when I call them :)

I also try to allow myself some "free thinking" time every day, where I will typically go for a walk and let my mind wander. That's usually where my best ideas come from.

The evening is trickier since the US is still awake when I go to bed. But I need to set boundaries, for myself and my family. So I will drop my phone in the office when I come in, check it again after the kids are asleep, and then charge it in the office. I recently bought an old-school alarm clock so I don't need the phone to be next to my bed.
