:PROPERTIES:
:ID:       9980ae28-68d4-4e29-9248-d661ccd85ab8
:END:
#+title: 💻 Working on now
#+filetags: :public:

- I implement MCMC samplers in [[https://github.com/blackjax-devs/blackjax][blackjax]].

  Blackjax is approaching v1, and will go through API consolidation soon. I have to admit I particulatly enjoy tweaking APIs until they feel "natural" (which probably means "I'm used to it"). We are seeing more applications of =blackjax= to deep learning, and looking forward to examples that distribute gradient computations.

- I build MCMC samplers automatically with [[https://github.com/aesara-devs/aemcmc][AeMCMC]]

  We use /miniKanren/ to match models with the samplers that is most appropriate, and reparametrize models automatically.

- [[https://github.com/pollsposition][Politics and statistics]] with [[id:51550685-38f7-4cbd-8fd4-bd0c5c293c04][Pollsposition]].

  I am currently building a model to [[file:blog/drafts/presidentielles-report-voix.org][infer vote transfers]] between the first and second round of the presidential elections. I am also rewriting all my models with [[id:5a5e87b1-558c-43db-ad38-32a073b10351][Aesara]] and [[https://github.com/blackjax-devs/blackjax][Blackjax]], writing down an introdution to our model. We are always looking to add more data to the [[https://github.com/pollsposition/data][repository]].

- I answer my own questions [[https://www.ddoxa.fr][in public and in french]] (these should probably moved to this repository).

I am also trying to [[id:058ec62c-6022-4eeb-b0a0-e88a75a8b761][do other things with my life]].

* Interests

- [[id:bf925a86-18be-4845-ad88-063a28f359f4][Democracy]]
- [[id:1a53642d-c03e-4ae9-92e2-e164869927b3][The monetary system]]
- [[id:f9dc079d-0b83-4ab5-afc4-c3a7045fb6a9][Symbolic and relational programming]]
- [[id:5acc4f0f-417e-424f-95a5-1c95e7e822ff][Markov Chain Monte Carlo]]
