:PROPERTIES:
:ID:       9b102ff7-98bc-4c73-8f3a-016c74c54f8e
:END:
#+title: Les hauts revenus paient pour le chômage des autres
#+filetags: :public:inprogress:

- tags :: [[id:3971d3ec-85c6-49dc-b1ad-54b935a641d8][Doxa]]

Depuis le 1er Octobre 2018 les cotisations chômage sont payées par l'employeur, à un taux constant de 4.05%. Petite subtilité: l'assiette de cette cotisation est plafonnée. C'est-à-dire qu'un taux fixe est appliqué sur l'intégralité de votre salaire, sauf si celui-ci dépasse un certain montant; auquel cas le taux est appliqué sur la partie correspondant au montant du plafond.

: illustration ici

Le plafond est fixé à 4 fois le plafond de la sécurité sociale, soit

#+begin_src python
plafond_secu = 3448
return 4 * plafond_secu
#+end_src

13792 euros / mois. Dans la même logique, le plafond de l'Allocation de Retour à l'Emploi est fixée à 256,96 € (grosso-modo équivalents, on ne va pas pinailler là-dessus).
A quatre fois le plafond on touche: 256.68 euros/jour (7700.40 euros bruts / mois) pendant 182 jours puis 179.68 euros pendant 548 jours

** TODO Statistiques chômage / revenu


On a les effectifs par tranche de salaire.
On a des déciles bizarres pour le montant.

** TODO Distribution revenus
** TODO Distribution allocations chômage
** TODO Cotisations sociales, comment ça marche?

** Références

- https://statistiques.pole-emploi.org/indem/publication
- Code source calcul de l'ARE: https://www.pole-emploi.org/opendata/calcul-de-lallocation-daide-au-r.html?type=article
