:PROPERTIES:
:ID:       bf925a86-18be-4845-ad88-063a28f359f4
:END:
#+TITLE: Democracy
#+FILETAGS: :notebook:
#+CREATED: [2022-03-06 Sun 17:51]
#+LAST_MODIFIED: [2022-05-27 Fri 10:19]

δημοκρατία, dēmokratiā, from dēmos 'people' and kratos 'rule

The purpose of this notebook is to study the history of democracy with a focus on ancient Greece and the United States, and learn whatever lesson there is to learn, if any. The topic of democracy is paramount in politics, because it [[id:894ff6dd-196e-4358-b26b-645b09ca892e][takes precedence over almost every other concept]] in the sense that it can be used to justify many measures, such as [[id:41209f8c-5f1e-43e5-83bc-742c25e4d97c][progressive taxation]].

Demcracy as a deliberation mechanism for [[id:f3ce8558-f64a-433a-9ceb-ce35a45aa02e][Collective Cognition]], and [[id:eccc7518-b461-45db-a19c-dd1854ba88e0][an efficient way for generating good ideas.]]

* Democracy: nuts and bolts

How it has been and is implemented in practice. What are the pros and cons?

* Can we make an argument in favor of democracies that is not a moral argument?

Maybe is it the most efficient way of governing people (in what sense?), to use its human resources. Maybe it gives a way for the most powerful to solve their conflicts without violence? Something else?

Lasch in /[[id:cbfef2ef-f24c-402e-93e1-82f03a5c9e54][The Revolt of the Elite]]/ makes the case that democracy is the most educational form of government, and agrees with Hannah Arendt that it precedes equality: it is a way to reach equality.

#+description: Christopher Lasch. The Revolt of the Elite (page 88).
#+begin_quote
[T]he enlightment got it backward. It is citizenship that confers equality, not equality that creates a right to citizenship.
#+end_quote

* What makes for a thriving democracy?
* What threatens democracy?
* Are western democracies, democracies?

* Online

- The Scholar Stage's [[https://scholars-stage.org/pining-for-democracy-a-few-readings/][Pinning for Democracy: a few readings]] for a list of readings on the American democracy.
- [[https://plato.stanford.edu/entries/democracy/][Article]] on the Stanford Encyclopedia of Philosophy

* Books

- Elizabeth Anderson, Private government: how employers rule our lives (and why we don't talk about it)
- Hélène Landemore, Open democracy (2020)
- William Nelson, On justifying democracy (2012)
- Aristotle, The Athenian Constitution
- Josiah Ober
  - Mass and elite in democratic Greece (1991)
  - Democracy and Knowledge (2008)
  - The Rise and Fall of Classical Greece (2015)
- Moses I. Finley, Democracy Ancient and Modern (2018)
- Loren J. Samons, What's wrong ith democracy? (2004)
- Thomas Seeley, Honeybee democracy (2010)
- Alexis de Tocqueville, De la démocratie en Amérique (1845)
- Daniel W. Howe, What Hath God Wrought: The Transformation of America (2007)
- Harry L. Watson, Liberty and Power: The Politics of Jacksonian America (2006)
- Frank M. Bryan, Real democracy - The New England Town Meeting (2003)
- Theda Skocpol, Diminished Democracy (2021)
- Sheldon S. Wolln, Democracy Incorporated: Managed Democracy and the Specter of Inverted Totalitarianism (2017)
- Robet A. Dahl, Democracy and its critics (1991)
- Bryan Caplan, The Myth of the Rational Voter – Why Democracies Choose Bad Policies (2008)
- Steven Levitsky, How democracies die (2019)
- Jason Brennan, Against democracy (2016)
- Robert Putnam, Bowling alone (2000)
- Christopher Lasch, The revolt of elites & Betrayal of Democracy (1997)
- Charles Murray, Coming Apart (2012)
- Christopher H. Achen & Larry M. Bartels, Democracy for the realists: Why elections do not produce responsive governments (2016)
- Matt Grossmann, Artists of the Possible: Governing Networks and American Policy since 1945 (2014)
