:PROPERTIES:
:ID:       894ff6dd-196e-4358-b26b-645b09ca892e
:END:
#+TITLE: Democracy takes precedence
#+CREATED: [2022-02-15 Tue 18:02]
#+LAST_MODIFIED: [2022-04-06 Wed 15:52]

- tags :: [[id:bf925a86-18be-4845-ad88-063a28f359f4][Democracy]]

Democracy takes precedence over many concepts. By that I mean that one does not need anything but democracy as an ideal to justify these concepts. [[id:41209f8c-5f1e-43e5-83bc-742c25e4d97c][Progressive taxes are justified by the need to preserve democracy]], for instance: if you don't enforce progressive taxation you risk corruption and people accumulating power that is in competition with people's right to vote. [[id:88128fec-69c4-4e2d-92ec-303e448cc56c][States raising funds on financial markets is also a threat to democracy]]: while market pundits will argue markets are democratic, in practice you are signing yourself up for oligarchy: 50% of the US' sovereign debt is owned by 1% of the population. And people who loan money to the State are more likely to be heard than others.
