:PROPERTIES:
:ID:       0d6b8742-3482-48e0-adb5-1a9a885f4ad6
:END:
#+TITLE: Build a collective brain
#+CREATED: [2022-05-23 Mon 17:31]
#+LAST_MODIFIED: [2022-05-24 Tue 10:00]

Collaborating on knowledge is hard. Organizations that are supposed to provide a setting for collective thinking, like think tanks, often fall short. Informations are hard to find, it is often hard to see where the original information comes from etc.

Complex thoughts are also very intricated. It is very hard, for instance, to write a report on climate change mitigation without invoking industrial and energy production strategy, which are topics in their own right. In reality, /topics overlap because they are the combination of atomic thoughts/.

*Insert example of such atomic thoughts*

- Nuclear energy is low-carbon
- Nuclear energy is safe
- France imports its Uranium

Here are the constraints we are taking into account:
- Participants have little time to contribute;
- Invited collaborators have even less time to contribute;
- Most readers are often interested in a few point;
- Read want to source intforma

* TODO How is it linked to wiki?

* Atomic notes

Notes have one simple conclusion that can be referenced in other notes. They are *units of knowledge* and are written so they can stay /evergreen/. Examples are:

- "Nuclear energy is a low-carbon energy"
- "Nuclear energy is safe"

And notes contain supporting evidence, graphs etc.

Working with atomic, evergreen notes has several purposes:
- We can easily collaborate without impeding on each other's work;
- We can ask for help on /very specific/ topics (instead of collaborations on a whole report, which can take a lot of time);
- We can contribute even when we have very little time;
- Work can easily be interrupted
- Old reports still refer to up-to-date evidence.

*Notes are an interface to an idea*.The concept is the interface, and everything that supports this concept is hidden in the note. This means we can use notes as legos; details do not matter. Similarly to computer programming the art of writing notes is thus the art of finding the correct interafce, the right level of granularity. Once we have the right interface we can call them in support of other concepts.

*Knowledge accumulates*. Writing reports and refering to them is a messy process. Here we are sure that knowledge accumulates over time, which is not guaranteed by any other system.

* Links are updated and reflect dependence

Notes can make use of the conclusion of other notes to output a new conclusion.

*Graph is the current state of knowledge: concepts and how they are connected.* It is frequent to "discover" relations between concepts and adding them while exploring the graph.

Notes should be densely connected.

If notes are well-connected it is much easier to propagate corrections from an existing notes. When I modify the note "France imports most of its Uranium" because of a change in policy, I am able to see the notes that were referencing this conclusion, and potentially change their conclusion, and propagate this change, etc. Changes are propagated recursively until no correction is needed anymore. If the links are up-to-date this process ensures that everything that needs updating is updated.

If only the evidence to a note is changed, but the conclusion is not changed then no other note is affected!

/Good structure allows to propagate conclusions./

* Reports are timestamped snapshots

They are perishable: they may be missing concepts or the way they organize concepts may not be optimal. But since notes reference concept notes, readers can at all time check the supporting evidence.

But because reports are still available, if concepts become void we need to keep the note, indicate it is and explain why. We then propagate changes through the graph.

* Technical solution

*Vizualising notes is paramount*
- It is interesting to have a full list of a note's parents at the bottom of a note;
- But also see the notes that are 2-3 steps away from the note represented as a graph. This is how most connections are made.
- And finally there should be a view of the full graph somewhere

*We can measure graph properties*

** Logseq
How can we collaborate on logseq
** Regular export to a static website
** Org-roam
