:PROPERTIES:
:ID:       cbfef2ef-f24c-402e-93e1-82f03a5c9e54
:END:
#+TITLE: The Revolt of the Elites and the Betrayal of Democracy
#+CREATED: [2022-05-09 Mon 17:39]
#+LAST_MODIFIED: [2022-05-10 Tue 13:27]

There is an intensification of social division, and a decline of the democractic discourse.

* The Revolt of the Elite (two)

Lasch spends a great deal of time criticizing what he calls the /[[id:5a4a1582-6dee-4e42-96af-e45e17ad0659][privileged class]]/, the top 20%. It is an /arrogant/ elite which thinks of itself as /self-made/ which owes its priviledge only to its own efforts. But [[id:94270311-8c8c-442e-a5f6-016a524202f6][meritocracy is a privilege-laundering scheme]]:

#+begin_quote
Although hereditary advantages play an important part in the attainment of professional or managerial status, the new class has to maintain the fiction that its power rests on intelligence.
#+end_quote

Lasch argues that /meritocracy/ has replaced democracy for the worse. Opportunities for advancement for a few individuals are no substitute for the general advancement of means of civilization and "dignity and culture" needed by *everyone*. In addition, [[id:cfbe99dd-aef4-40f7-973a-969483550250][meritocracy nullifies the opposition]]:

#+description: page 43
#+begin_quote
[M]eritocracy has the effect of making elites more secure than ever in their privileges (which can now be seen as the appropriate reward of dilligence and brainpower) while nullifying working-class opposition.
#+end_quote

#+description: page 44
#+begin_quote
it drains talent away from the lower class and thus deprives them of effective leadership.
#+end_quote

The privileged has made itself independent. It has no nationality, does not belong to anywhere and as a consequence it does not feel responsible for the lower class, and is not ready to make any sacrifice. They do not "subscribe to a theory of noblesse oblige".

#+description: page 45
#+begin_quote
Many of them have ceased to think of themselves as American in any important sense, implicated in America's destiny for better or for worse.
#+end_quote

#+description: page 47
#+begin_quote
Without national attachment [...] people have little inclination to make sacrifices or to accept responsibility for their actions.
#+end_quote


* Opportunity in the promised Land (three)

Upward mobility entered everyday speech in the wake of the Great Depression it has not decreased divisions in society, quite the opposite. And rates of mobility have remained more or less constant.

#+description: page 53
#+begin_quote
Having internalized the myth of the self-made man, workers have too often sacrificed solidarity to the illusory hope of individual advancement.
#+end_quote

It is not about increasing quality but about increasing consideration. We are optimizing for the wrong thing.

#+begin_quote
Both [ndlr: sides in the argument for Affirmative Action] see careers open to talent as the be-all and end-all of democracy when in fact, careerism tends to undermine democracy by divorcing knowledge from practical experience, devaluing the kind of knowledge that is gained from experience, and generating social conditions in which ordinary people are not expected to know anything at all. The reign of specialized expertise--the logical result of policies that equate opportunity with open access to "places of higher consideration"---is the antithesis of democracy as it was understood by those who saw this country as the "last, best hope on earth".
#+end_quote

and notoriously Lincoln who saw in property the opportunity for labourers to fully realize their potential. Democracy is about allowing everyone to fully realize their potential.


* Does democracy deserve to survive? (four)

Envisionned that democracy would turn into an obsession with fanaticism on one side and racial warfare on the other. Complains that debates amounts to describing the other side as "socialist" or "fascist".

Opposes Lippmann's view that "public opinion is necessarily ill-informed and that government is best left to specialists".

#+description: page 88, referring to Hannah Arendt
#+begin_quote
[T]he enlightment got it backward. It is citizenship that confers equality, not equality that creates a right to citizenship.
#+end_quote

#+description: page 88
#+begin_quote
Political equality---citizenship---equalizes people who are otherwise unequal in their capacities, and the universalization of citizenship therefore has to be accompanied not only by formal training in the civic arts but by measures designed to assure the broadest distribution of economic and political responsibility, the exercise of which is more important than formal trainingg in teaching good judgment, clear and cogent speech, the capacity for decision, and the willingness to accept the consequences of our actions. It is in this sense that /citizenship implies a whole world of heroes/.
#+end_quote

Lasch insists on the fact that tolerance has taken a bigger role than ethics:

#+description: page 89
#+begin_quote
We are determined to respect everyone but we have forgotten that respect needs to be earned.
#+end_quote


* Communautarianism or populism? (five)
