:PROPERTIES:
:ID:       18aa0ee6-aa31-42f8-b0b0-9064d38dbfdc
:END:
#+TITLE: We have an entropy issue with finance
#+CREATED: [2022-01-11 Tue 19:33]
#+LAST_MODIFIED: [2022-01-11 Tue 19:47]

There is an inherent /engineering complexity/ that has kept piling up for decades now; de-regulation meant giving more free variables to banks and other actors. Which would be ok if the interface between these actors and the real-world had also worsened. For instance, the interface Central Banks created from the financial sector and themselves / the "real" economy has become more complex over time as well.

Strangely finance goes against progress, which is about [[id:6c148b45-66c2-42f9-afe0-76a2df38e8c7][reducing the number of things we need to think about]].

Finance will eventually need to be contained, and this can be done in two way:
- Reduce the engineering complexity by putting more constraints on the system. [[id:8075ac29-97a9-495a-86c6-c04a0c2aa4d0][Democracy is what reduces entropy]]. Going back to the [[id:03cc90e2-d0c2-459d-8867-194bb4822c71][Bretton-Woods system]] for instance.
- Contain the engineering complexity with reducing the surface area that we need to control.
