:PROPERTIES:
:ID:       d5e315a6-4d22-4fac-9e65-9df064f5e7c3
:END:
#+title: Garden design

There is a strong biais towards /naturalistic gardening/. The idea behind this school of thought is to recreate the /feel/ of natural environments at a smaller scale. Indeed, random plantings like the ones that occur in the wild are usually boring since the typical size of gardens does not allow for structure to emerge. We thus have to "force" the emergence of these natural structures with the way plants are chosen and arranged.

[[id:f4cf39be-6c6a-4a9d-804a-3879a98177bc][Relational programming]] could be used to procedurally generate garden layouts.

- Russell Page. The Education of a Gardener. NYRB Classics. 2007
- Piet Oudolf, Noel Kingsbury. Planting: A New Perspective. Timber Press. 2013
  A good introduction to /naturalistic gardening/, general philosophy and planting strategies with real examples.
- Piet Oudolf, Henk Gerritsen. Planting the Natural Garden. Timber Press. 2019
  A very short and useful "encyclopedia" of the plants that are most used by the /natualistic gardening/ people. A quickl visual reference, some recommendations based on /moods/ (rather than color, shape, etc.)
- Noel Kingsbury, Claire Takacs. Wild, The Naturalistic Garden. Phaidon. 2022
  Many pictures of many great gardens. Great for inspiration, and looks great on you shelves.
- Rosemary Alexander, Rachel Myers. The Garden Design Workbook. Timber Press. 2017
  A very practical introduction to garden design. It is aimed at people who would like to start a garden design business, but good advice for every begginer.
