:PROPERTIES:
:ID:       03441375-96a3-45af-b991-03b6f14a6e06
:END:
#+TITLE: Dignity: Seeking Respect in Back Row America
#+CREATED: [2022-05-11 Wed 14:43]
#+LAST_MODIFIED: [2022-05-11 Wed 15:28]

Chris Arnade takes us on a very emotional journey through back-row America. A sobering one for people, like me, who Christopher Lasch would have described as the "privileged class". One portrait, one neighbourhood, one McDonald's at a time Chris paints the selfishness of the privileged class who decided to isolate itself.

#+description: page 46
#+begin_quote
We were well-intended, but we removed ourselves from the lived experiences of most of the country, included the places and people we wanted to help.
#+end_quote

Front-row people, as Chris calls them, created a world that was optimizing their vision of success /on average/. It was optimizing things that could be measured (economic growth), but not things that couldn't be easily measured. We inadvertedly destroyed their world. We find the same critique as in Lasch's [[id:cbfef2ef-f24c-402e-93e1-82f03a5c9e54][The Revolt of the Elites]] regarding meritocracy. When success is about going "upwards" and leaving your hometown, territories are sucked dry of talents, and they decay.

The "small losses" we were ready to have in the name of progress (e.g. factories closing) were actually *everything these people had*. /Average/ progress per capita is a /terrible/ measure. We're only as wealthy as the least wealthy of us.

#+description: page 106
#+begin_quote
"Our lives used to be centered around work and church. Now they're centered around McDonald's and church"
#+end_quote

Church and McDonald's have that in common that they host a non-judgmental community where there are no absurd rules.

People being called /dumb/ at school comes often in this stories.

"This is my HOME". HOME. HOME.

Cheap labor had an impact on unemployment (on top of factories moving). Reminds me of that Netflix documentary on a former GM plant that was bought by a Chinese company, where workers were paid almost half what they were paid with GM.

The theme that that supposed meritocracy brings humiliation comes back often:

#+description: page 232
#+begin_quote
Everyone wants to feel like a valued member of something larger than themselves. The current status quo doesn't do that for most of America, because it only understands value in economic forms of meaning.
#+end_quote

#+description: page 233
#+begin_quote
It is a system that applauds itself for being a meritocracy, allowing anyone to succeed. Implying that those who don't choose this path, who can't or don't pick up and move constantly, who can't overcome the long odds, are failures and it is their own fault.
#+end_quote


"We all need to listen to each other more" = more democracy.

#+description: page 283
#+begin_quote
We have removed ourselved physically and in spirit, and when we do look back, it is through papers and books filled with data. We study poverty and those left behind with spreadsheets and statistics, believing we are well-intentioned, believing that we are really valuing them. Instead, we are diminishing them by seeing them simply as numbers to be manipulated.
#+end_quote
