:PROPERTIES:
:ID:       e9c4cc73-458d-4db4-b33e-9c71840ebc27
:ROAM_REFS: cite:carse2013
:END:
#+TITLE: Finite and infinite games.
#+CREATED: [2022-02-07 Mon 14:03]
#+LAST_MODIFIED: [2022-02-07 Mon 14:05]

p15 - "Seriousness always relates to roles, or abstractions [...] Seriousness always has to do with an establishmed script"

p27 - "Titles are abstractions; names are always concrete"

p29 - "Too speak meaningfully of a person’s power is to speak of what that person has already completed in one or another closed field. To see power is to look backward in time.”

p33 - "Evil is never intended as evil. Indeed, the contradiction inherent in all evil is that it originates in the desire to eliminate evil."

NUMBER 31 IS THE SHIT

> As societies complexify we create more and more finite games to an extreme.

p39 - Political realities do not precede, but follow from, the essential fluidity of our humanness.

p48 - It is agreement that establishes force. Those who consent to a society’s constraints see them as constraints.

Property must be seen as compensation. Risk, talent, etc

p57 - "where a society is defined by its boundaries, a culture is defined by its horizons”

p61- War presents itself for self-protection, when in fact it is necessary for self-identification.

p103 - The unspeakability of nature is the very possibility of language. History is the realm of the speakable however.

p105 - reread about explanations as a response to inadequacies in knowledge
