:PROPERTIES:
:ID:       cbfef2ef-f24c-402e-93e1-82f03a5c9e54
:END:
#+TITLE: The Revolt of the Elites and the Betrayal of Democracy
#+CREATED: [2022-05-09 Mon 17:39]
#+LAST_MODIFIED: [2022-05-09 Mon 18:15]

There is an intensification of social division, and a decline of the democractic discourse.

* The Revolt of the Elite (two)

Lasch spends a great deal of time criticizing what he calls the /[[id:5a4a1582-6dee-4e42-96af-e45e17ad0659][privileged class]]/, the top 20%. It is an /arrogant/ elite which thinks of itself as /self-made/ which owes its priviledge only to its own efforts. But [[id:94270311-8c8c-442e-a5f6-016a524202f6][meritocracy is a privilege-laundering scheme]]:

#+begin_quote
Although hereditary advantages play an important part in the attainment of professional or managerial status, the new class has to maintain the fiction that its power rests on intelligence.
#+end_quote

Lasch argues that /meritocracy/ has replaced democracy for the worse. Opportunities for advancement for a few individuals are no substitute for the general advancement of means of civilization and "dignity and culture" needed by *everyone*. In addition, [[id:cfbe99dd-aef4-40f7-973a-969483550250][meritocracy nullifies the opposition]]:

#+description: page 43
#+begin_quote
[M]eritocracy has the effect of making elites more secure than ever in their privileges (which can now be seen as the appropriate reward of dilligence and brainpower) while nullifying working-class opposition.
#+end_quote

#+description: page 44
#+begin_quote
it drains talent away from the lower class and thus deprives them of effective leadership.
#+end_quote

The privileged has made itself independent. It has no nationality, does not belong to anywhere and as a consequence it does not feel responsible for the lower class, and is not ready to make any sacrifice. They do not "subscribe to a theory of noblesse oblige".

#+description: page 45
#+begin_quote
Many of them have ceased to think of themselves as American in any important sense, implicated in America's destiny for better or for worse.
#+end_quote

#+description: page 47
#+begin_quote
Without national attachment [...] people have little inclination to make sacrifices or to accept responsibility for their actions.
#+end_quote


* Opportunity in the promised Land (three)
* Does democracy deserve to survive? (four)
* Communautarianism or populism? (five)
