:PROPERTIES:
:ID:       0dcfb52d-9bd2-4242-810f-22575be8c40f
:END:
#+TITLE: Having a job as a right
#+CREATED: [2022-05-12 Thu 08:42]
#+LAST_MODIFIED: [2022-05-12 Thu 08:50]

I am not a fan of legalism, but it is usefully to understand what the true motivation for the [[id:88bbaec1-0b44-40ab-985c-40c20d8fecb0][right to a job]] were at the time. What problem it was trying to answer and what reasons were invoked at the time.

The Preamble to the [[https://www.legifrance.gouv.fr/contenu/menu/droit-national-en-vigueur/constitution/preambule-de-la-constitution-du-27-octobre-1946][French Constitution of 1946]] (4th Republic), which is included in the [[https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000571356/2019-07-01/][French Constitution of 1958]] (5th Republic) states in its 5th article:

#+begin_quote
Chacun a le devoir de travailler et le droit d'obtenir un emploi. Nul ne peut être lésé, dans son travail ou son emploi, en raison de ses origines, de ses opinions ou de ses croyances.
#+end_quote

This right to in the [[https://www.un.org/fr/universal-declaration-human-rights/][Universal Declaration of Human Rights]] in 1948 in its 23rd article:

#+begin_quote
1. Toute personne a droit au travail, au libre choix de son travail, à des conditions équitables et satisfaisantes de travail et à la protection contre le chômage.
#+end_quote
