:PROPERTIES:
:ID:       ecdcbde7-c634-4b64-8159-145cb62b6ce1
:END:
#+title: Jardin

This corner of my digital garden is all about /real/ gardens; research, plans and observations that go in the making of my own garden.

* Entrance

* Pool

- Thin dark stone border, green-ish water. 15m long, maximum 4m wide (aspect ratio)
- Green grass all around the pool. Should not extend too far as grass needs watering in summertime and we want to limit that as much as possible.
- From the house the view should probably not extend much further beyong than the pool. We should block the view there.

* Slope around the terrasse

We need to do something with the slope around the terrasse. We step on it everytime we need to go somewhere, but it also offers some nice shade in the afternoon.

* Rose garden (tentative)

- This can be done in a second time

* Office

- The idea is to have a detached office made of wood that is camouflaged in a corner of the garden. Ideally we can use the area under the pine tree, where nothing will really grow.
- The office will be something like [[https://en.mywoodcab.com/instagram][MyWoodCab]] (Insulated, AC, electricty, shelves, etc.)
- We can "hide" the office behind a sea of perennials
- We need to keep some space in front of the wood storage, and a direct line from the house to the wood storage
- There should be a place to sit and have coffee next to (under?) the apple tree there as it is the only place in the garden that has shade in the morning.
- More generally this area of the garden has more shade than anywhere else so we can go for a different vibe.



* References

- Russell Page. The Education of a a Gardener. NYRB Classics. 2007
- Piet Oudolf, Noel Kingsbury. Planting: A New Perspective. Timber Press. 2013
- Noel Kingsbury, Claire Takacs. Wild, The Naturalistic Garden. Phaidon. 2022
