:PROPERTIES:
:ID:       ecdcbde7-c634-4b64-8159-145cb62b6ce1
:END:
#+title: Jardin

This corner of my digital garden is all about /real/ gardens; research, plans and observations that go in the making of my own garden. See the [[id:d5e315a6-4d22-4fac-9e65-9df064f5e7c3][Garden design]] notebook for references.

* Entrance

* Pool

- Thin dark stone border, green-ish water. 15m long, maximum 4m wide (aspect ratio)
- Green grass all around the pool. Should not extend too far as grass needs watering in summertime and we want to limit that as much as possible.
- From the house the view should probably not extend much further beyong than the pool. We should block the view there.

* Slope around the terrasse

We need to do something with the slope around the terrasse. We step on it everytime we need to go somewhere, but it also offers some nice shade in the afternoon.

Since the house faces South we will need some shade in the summer, while letting the light go through in the summer. [[https://coloradoencyclopedia.org/article/aspen-trees][Quacking aspen]] ([[id:e8d7cb42-01c9-4080-a323-c0f5b3cb644e][Populus tremuloides]]) would be a nice reminder of our family's origins. Their leaves make a very recognisable noise with the wind, and have a gorgeous golden color in fall. They're invasive, so that's something to consider. I'm also not sure we can import Populus tremuloides from the US in Europe (but we do have other members of the Populus genus available)


* Rose garden (tentative)

- This can be done in a second time

* Office

- The idea is to have a detached office made of wood that is camouflaged in a corner of the garden. Ideally we can use the area under the pine tree, where nothing will really grow.
- The office will be something like [[https://en.mywoodcab.com/instagram][MyWoodCab]] (Insulated, AC, electricty, shelves, etc.)
- We can "hide" the office behind a sea of perennials
- We need to keep some space in front of the wood storage, and a direct line from the house to the wood storage
- There should be a place to sit and have coffee next to (under?) the apple tree there as it is the only place in the garden that has shade in the morning.
- More generally this area of the garden has more shade than anywhere else so we can go for a different vibe.


* Nurseries

- [[https://vivaces-en-conteneurs.com/catalogue.html][Pepiniere Chombart]]
- [[https://www.lepage-vivaces.com/][Pepiniere Lepage]]
