:PROPERTIES:
:ID:       5baed631-d4de-405c-95e3-61845c658756
:END:
#+TITLE: You can probably assume people behave randomly
#+CREATED: [2022-01-16 Sun 20:25]
#+LAST_MODIFIED: [2022-04-06 Wed 15:41]

- tags :: [[id:5fecd21c-5701-48af-9fd8-a2a2ab9b36a8][Economics]]

In neoclassical [[id:5fecd21c-5701-48af-9fd8-a2a2ab9b36a8][economics]] agent rationality is central in the microfoundations of the supply & demande curve. Not only is the validty of this assumption is shattered by the [[id:2dc3d1ec-10f3-4c86-8688-705053838390][Sonnenschein-Mantel-Debreu (SMD) theorem]], it is probably not necessary. Unless we have a good reason to assume they are rational (it is a /big/ assumption) then we'll have to do as if they were behaving randomly, hoping some emergent behavior appears and can be quantitied [[cite:&smith2017]]

What counts then, and what will shape the emergent behavior is the set of possibilities. If agents become correlated (bank run for instance) it is only the way the opportunity set is explored that changes, not the set itself. That would mean that [[id:2120067a-2060-4c76-ab07-f61598a450bc][At a macro level we should only be concerned with possibilities]].

* References

- Jason Smith, [[id:0643e77a-2f30-4143-94b5-6b44051a22ef][A Random Physicist Takes on Economics]]
