:PROPERTIES:
:ID:       18aa0ee6-aa31-42f8-b0b0-9064d38dbfdc
:END:
#+TITLE: We have an entropy issue with finance
#+CREATED: [2022-01-11 Tue 19:33]
#+LAST_MODIFIED: [2022-04-08 Fri 09:19]

There is an inherent /engineering complexity/ that has kept piling up for decades in finance. On the one hand we gave it more degrees of freedom, for instance with the end of [[id:03cc90e2-d0c2-459d-8867-194bb4822c71][the Bretton-Woods system]], removing barriers to the free circulation of capital, ect. But on the other hand we had to compensate for the consequent failures with more regulation: [[id:f0362341-e64f-4fa4-a279-d09415d08d18][Basel I]], [[id:7ebbf133-eb87-47b8-980d-6895a557dc14][Basel II]], [[id:ff5835b8-780c-4a2f-97b2-efe3650a9eba][Basel III]]. Leading to a Rube-Goldberg machine that few people, if any, understand completely.

In a way the financial system goes against progress, which is a lot about [[id:6c148b45-66c2-42f9-afe0-76a2df38e8c7][reducing the number of things we need to think about]]. Indeed, it interfaces with the nuts-and-bolts economy in so many ways (because [[id:3a0e116a-1a3c-4ea8-8a5c-d491b4350e1f][A lot finance is plumbing for the economy]]) that increase in complexity translates in the rest of the economy.

Complexity is responsible for:
- Loss of information as the system becomes more opaque;
- Uncertainty, in the sense that participants know that they cannot know;

Indeed, complexity is not synonymous with stability [ref needed].

* The system needs to be simplified

The system will eventually need to be contained more than it currently is, because:
- As crises have repeatedly shown us, it is very vulnerable;
- It certainly doesn't /need/ to be so complex. There's a part that's very valuable to nuts-and-bolts economy, but probably [unsubstantiated] a larger part that is not.

We thus have 2 levers to pull:
- *Reduce the engineering complexity* by putting more constraints on the system. Going back to the [[id:03cc90e2-d0c2-459d-8867-194bb4822c71][Bretton-Woods system]] for instance.
- *Contain the engineering complexity* with reducing the surface area that we need to control.

This choice will not happen organically, and must be channelled through a democratic decision. The democratic process, after all,  [[id:8075ac29-97a9-495a-86c6-c04a0c2aa4du][is great at reducing entropy]].

* References
- Hyman P. Minsky. "Stabilizing an unstable economy" (1986)
  #+begin_comment
TOREAD
  #+end_comment

- Kambhu, John, Neel Krishnan, and Scott Weidman. [[http://elibrary.pcu.edu.ph:9000/digi/NA02/2007/11914.pdf]["New directions for understanding systemic risk"]] Economic Policy Review 13.Nov (2007).
  #+begin_quote
The stability of the financial system and the potential for systemic risks to alter the functioning of that system have long been important topics for central banks and for the related research community. However, recent experiences, including the market disruption following the attacks of September 11, 2001, suggest that existing models of systemic shocks in the financial system may not adequately capture the propagation of major disturbances. For example, current models do not fully reflect the increasing complexity of the financial system’s structure, the complete range of financial and information flows, and the diverse nature of the endogenous behavior of different agents in the system
  #+end_quote

- Andrew Haldane (Bank of England): [[https://www.bis.org/review/r090505e.pdf][Rethinking the financial network]] (2009)
  #+begin_comment
Very thourough (and long) paper with references to other complex systems that are interesting.
  #+end_comment

  #+begin_quote
The past 18 months have revealed a system which has shown itself to be neither selfregulating nor self-repairing. Like the rainforests, when faced with a big shock, the financial
system has at times risked becoming non-renewable.
  #+end_quote

- Jean-Pierre Landau (Banque de France): [[https://www.bis.org/review/r090806c.pdf][Complexity and the financial crisis]] (2009)
 #+begin_quote
 Overall, complexity may have resulted in more fragility, an evolution already foretold by Minsky who saw structural changes in financial systems over time as an essential cause of their vulnerability
 #+end_quote
