:PROPERTIES:
:ID:       abce7e33-2662-48fe-ac2a-496df464d106
:END:
#+title: Literature notes should be kept separate
#+filetags: :public:

For a while I thought that literature notes were useful for two reasons:
- We can /refer/ to the book's contents with others;
- A book allows to jump from one idea to another, it would add links between concepts

What made me question this is /visualizing my notes as a graph./

- Links should be between ideas that we formulated ourselves. The links are as much part of our second brain as the notes' contents. We should not let anyone's thought process and orgranization interfer with ours. We can create links between ideas we extract from ths book and reference this book on boh notes, but not link to the literature note.

This now [[id:a9d4499d-b5f4-4676-8ada-f7a5a5c38681][How I take reading notes]].

If the main motivation is to share a book review, then this is a project. Because [[id:d6361b63-7810-4322-8951-88eb05a9d882][Projects are what we write for others]], and [[id:ea76698c-b228-4eca-818d-0cb675b05130][Book reviews are not literature notes]]

[[cite:&ahrens2017]]
