:PROPERTIES:
:ID:       4eb2433c-fb92-4048-ba2f-1a9ba5d0c12c
:END:
#+title: Set up a log to dump everything

A garden quickly becomes cluttered, and can quickly become unmanageable; [[id:36a480da-b67f-4f55-8d17-fac346127e40][you need to curate your garden]]. One of the reasons why the typical set was getting cluttered is that there was no buffer between ideas that pop in my head and the website (I [[id:9b92383e-727d-4d16-9591-9730222e2d5c][publish my notes instantly]]). At the same time, I felt I was loosing a lot of material when I was on the go and didn't have access to my machine and emacs. I needed a log to dump everything in. This way:

- A lot of low-quality material, half-baked ideas don't make it here;
- I also don't loose anything. I /know/ everything is in there and that I can retrieve it later. I try to meditate more to not get attached to ideas so much, in the meantime dumping does it for me.

I originally tried solutions that were closer to the technology I use for this site ([[https://logseq.com][logseq]], editing org files directly). But I am optimizing for /efficiency/ here (and you should too): I just want to log the thought or the reference in a few seconds, and move on with my life. Integration with this website can be done when I am on my computer.

I use Notion which has a mobile app, and exports the log as a webpage: [[https://soundslab.notion.site/soundslab/Log-c873cc5909e54faf91590c68a587841c][here is the log]].
