:PROPERTIES:
:ID:       541043ea-fadc-41a3-a658-f9b7cda41a69
:ROAM_REFS: cite:ahrens2017
:END:
#+title: How to take smart notes: one simple technique to boost writing, learning and thinking  for students, academics and nonfiction book writers
#+filetags: :bibliography:

* Notes :noexport:

/This system is  GTD but for knowledge workers with very loosely defined goals/
- Writing is thinking and most thinking is mediated by writing, it is a very important skill to master;
- /Maintaining a good system should not a matter of willpower/ (we have very little of it) but by making the right workflow effortless;
- Process fleeting notes regularly

Project notes (related to only one project) should be out of the main system. What is and what is not a project note is really hard to define. Book gives clues on p46:
- outlines
- snippets
- to do
- draft
- code

- /Zeigarnick/: writing down things allows our brains to stop thinking about them
- Lit notes and book review are different things
- Some titles are definitive sentences, some are questions we don’t have an answer to
- They actually never say anything about research in progress

On p.143 - it says that these notes make you a better thinker as they allow you to test your abilities more times against a smaller workload. Progress is more easily measured in small chunks.

On p.146 - you are going to fail if you radically change your habits. Strategically build them up. Start with the inbox.

** Bibliography notes

We write Bibliographic notes so that, once we are done reading the book, we can come back to them and:
- Add new permanent notes or stubs
- Add content to existing notes ("behind" them in the original method)
- Create new links between notes

Bibliographic notes must be written with an /intention/ in mind, but the volume does not matter much: as needed.

** Practical Tips

- Remarkable note name should follow bibtex reference name =AuthorYear=
