:PROPERTIES:
:ID:       290974e3-81d9-4748-948d-93b1ec43a09c
:END:
#+TITLE: The Consumer Price Index is not actionable
#+CREATED: [2022-01-15 Sat 16:02]
#+LAST_MODIFIED: [2022-01-17 Mon 05:58]

- tags :: [[id:5fecd21c-5701-48af-9fd8-a2a2ab9b36a8][Economics]] [[id:d0110ef7-f82f-4568-bb0d-9ac077994b8e][Inflation]] [[id:b5f5e019-e22f-49b6-bfb5-ef03c8b0c41b][Consumer Price Index]]


The Consumer Price Index is often used as a proxy or inflation. It was meant as a desciption, a mere state of affairs. But it is not actionable, it does not tell us exactly what is making the prices increase and how they are increasing. It is all veyr obvious and yet people are using this as a proxy for the general increase in prices levels.


Two facts need explaining:
- The CPI has kept increasing since the 1940s
- [[id:7be372a6-07f8-4ee7-b12c-5a9747c46c83][The CPI has been increasing faster since the 70s]]


* Decompose the CPI

The CPI is computed using price indices computed monthly in different locations in the US. The data can be found on the [[https://download.bls.gov/pub/time.series/ap/][website of the Bureau of Labor Statistics]]. We can also find the [[https://www.bls.gov/opub/hom/cpi/calculation.htm][methodology]] on the website.


* TODO Look at components of CPI versus time for each area (plot w/ low alpha) :noexport:
* TODO Use Gaussian process to fit the curves?? :noexport:
* TODO Show distribution of area-based CPIs :noexport:
* TODO Show average evolution :noexport:
