:PROPERTIES:
:ID:       8075ac29-97a9-495a-86c6-c04a0c2aa4d0
:END:
#+TITLE: Democracy is what reduces entropy
#+CREATED: [2022-01-11 Tue 19:37]
#+LAST_MODIFIED: [2022-04-06 Wed 15:52]

- tags :: [[id:bf925a86-18be-4845-ad88-063a28f359f4][Democracy]]

Democracy (the vote) mediates the opinion of everyone to make a decision over one thing. Where a decentralized system would have led to more chaos. There is a tradeoff to be found between entropy reduction (ultimately authoritarian) and completely chaotic. I guess that's what designing representative systems and voting systems is about. [[id:034d2ee6-65c8-4e9e-973d-a5f21150950c][Complexity is an issue for societies]]

Decentralizing decision too much leads to an unnecessary increase in entropy. In this sense "the market" (whatever this means, [[id:b3757c5d-c47a-4b40-b34c-211061c71550][there is no such thing as "the market"]]) cannot be an efficient solution. Asking everyone at a given point in time what they want and enforcing that choice is the best information transfer mechanism we can think of. This seems to be an argument in favor of /more democracy/, as in Switzerland.
