:PROPERTIES:
:ID:       aeef5071-8a7c-4564-b270-c598127882b3
:END:
#+title: We can borrow at lower interest rates thanks to the Euro

- tags :: [[id:f6592dcf-e288-4c9f-a231-2d4a9ea88501][Euro]]

As the argument goes the commonon currency increases the liquidity of obligations on /secondary markets/,  which increases the demand and thus lowers the interest rate.

Greece is often cited as an example. In the 90s no one wanted to buy bonds in drachma and the introduction of the euro made it easier to resel them on the secondary market. South Korea has higher interest rates than the eurozone for instance. Even Germany.

*But* interest rates started to converge after Maastricht but before the introduction of the currency. So convergence might be due to hope in european solidatiry when it comes to sovereign debt. And hope in economic integration : for instance Germany suddenly has a bigger market. This hope completely plummeted after 2008 and we observed divergence again.

*Yes but* we are talking about bonds with distant maturity terms, and investors know they will be able to resell them in euros.

With different maturity.

*Ok* liquidity is a necessary condition for interest rates to go down. But since 2008 we know this is not a sufficient condition, so I am really wondering if convergence did not happen because of this promise.

Well interest rates are still lower than in 1997 for every country of the eurozone. Quantitative Easing increased liquidity on markets.

I would say this is rather due to Draghi's "whatever it takes", and QE means you get your money back even if country is on the verge of default. I am trying to disantangle the effect of the /existence/ of the common currency and of the political atmosphere around it.

Hard to distinguish the two effects. Would Bank of Greece saved its country with "whatever it takes" ?

This implies effect of confidence in the currency itself.

Yes. But *note that the interest rates on British bonds is higher than in the eurozone*.

Ok, that's a good argument in favour of the currency itself since there is no reason to not trust the pound and/or Bank of England.

* TODO Find a way to look at the interest rate vs liquidity
* TODO Plot interest rates accross euro zone from 1980s to today
* TODO check that QE inncreased liquidity in bond market.
* TODO Check if the volume exchanged of bonds is linked to the interest rates and if so in what sense the causality acts.
