name: Publish the typical set

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get --yes --force-yes install build-essential sqlite3 emacs

      - name: Build the html from org files
        run: |
          make publish

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _public
          CLEAN: true
